donkey/__init__.py, donkey/utils.py, scripts/drive.py
- Changed RPi detection to use machine, i.e. uname[4].startswith("arm")
- Moved envoy import within function (used only in one place)
- Misc fixes
=> RPi detection, imports

Dockerfile
@wroscoe this is the Dockerfile I used to create the docker image at https://hub.docker.com/r/alanwells/donkey-server-jessie/. I updated the dockerfile and image yesterday to match the recent directory structure changes. I thought it might make sense to include it in the repo.
=> Add dockerfile for server

donkey/templates/static/main.js, scripts/sdsandbox_drive.py
This is code written by alan but the pull request had big files I just deleted.
=> add joystick support & simulator support

donkey/templates/base.html, donkey/templates/session.html, donkey/templates/static/style.css
This PR adds:
- a more performant method of selecting multiple images on the session page
- select all capability for images on the session page
- removes a CSS selector that always marked the Pilots navigation tab as active.
=> Session UI updates (without whitespace changes)

donkey/actuators.py
Requires rrb3 library: 
$ cd ~
$ git clone https://github.com/simonmonk/raspirobotboard3.git
$ cd raspirobotboard3/python
$ sudo python setup.py install
=> Added support for RasPiRobot motor driver

config/vehicle.ini, donkey/__init__.py, donkey/actuators.py, donkey/config.py, donkey/models.py, donkey/pilots.py, donkey/remotes.py, donkey/sessions.py, donkey/templates/vehicle.html, donkey/vehicles.py, scripts/drive.py, scripts/sessions_to_hdf5.py, scripts/simulate.py
* Update vehicle controler to toggle on local pilot
* Update drive loop to separate remote from pilot
[ ] allow local steering and remote throttle.
=> Add drive mode to run local models

docs/how-it-works.md
I made notes as I was walking through the code to understand it. Hope this is useful for others.
=> Wrote documentation on structure of donkey code

start-server.sh
See
https://stackoverflow.com/questions/44557347/why-do-i-get-an-error-when-i-try-to-run-donkeycar-server-using-the-docker-image
for details
=> Fix: startup script was throwing FileNotFoundError

donkeycar/templates/donkey2.py, donkeycar/templates/donkey2_with_joystick.py, donkeycar/templates/square.py
Hi @wroscoe - it looks like I didn't have to touch the code around `index` in `Tub` to make train to take multiple tubs. But I might have overlooked something.
=> Multiple tubs for train command

docs/guide/train_autopilot.md
=> Added a few training tips at the end of the training_guide.md

docs/guide/get_driving.md, docs/parts/controllers.md
sorry, I missed getting these in before last merge.
=> joystick doc fixes

docs/guide/get_driving.md, docs/utility/donkey.md, donkeycar/management/base.py, donkeycar/parts/stores/tub.py, mkdocs.yml, setup.py
added utility to create a movie from tub dir. This adds a new dependency on moviepy. I tried to get things to work with just opencv, but failed to work as well as moviepy. docs updated to include new operation, as well as a few others in the `donkey` command that needed detailing.
=> Movie from tub

donkeycar/templates/donkey2.py
This makes it easy to create plots for checking model performance (very similar to some of the charts that @wroscoe has in some of his notebooks). 
Here's an example:
=> Add plot_predictions method to template

.gitignore, donkeycar/management/tub.py
* Use pandas for tub index. 
* Option to load preloaded model.
Minor changes:
* sort tubs in tub editor
=> V 2.2.0 - better tubs, opencv, bug fixes

docs/contribute.md, docs/guide/calibrate.md, docs/guide/get_driving.md, docs/guide/install_software.md, docs/guide/simulator.md, docs/guide/train_autopilot.md, docs/parts/about.md, docs/parts/controllers.md, docs/release.md, docs/utility/donkey.md
Made spelling and clarity fixes to the documentation.
=> Spelling and clarity

docs/parts/controllers.md
I've updated the docs to more accurately reflect the Playstation joystick controller charging problem.  It's kind of a trivial update, but helps me understand the process of contributing.
=> Update controllers.md - trivial update, but helpful to me to undersanding "pulling"

docs/guide/install_software.md
Update login and network location to match the current pre-built install that is referenced at the beginning of the tutorial.
=> Update install instructions

donkeycar/parts/actuator.py, donkeycar/templates/donkey2wh.py
new template is described as a difference to base template.
=> added hbridge part and two wheel steering

docs/roll_your_own.md, docs/supported_cars.md
Add a document that talks about how to choose or adopt other cars, and what to look for in cars you want to use.
Also add a link to said document.
=> Add a document that talks about how to choose or adopt other cars

docs/faq.md, mkdocs.yml
Also update faq.md
Note: mkdocs now complains, but the link generated works. Bug!
=> Fix the broken link to supported_cars.md.

install/make_pi_disk_img.sh
=> Modify error parameters

docs/guide/calibrate.md
I tried to run calibration by going into the donkey environment on my Mac instead of ssh-ing into my Pi. Hopefully adding this line will enable others to avoid my mistake and wasting time.
=> Clarification on how to begin calibration

docs/guide/build_hardware.md
sava color in stock and similar price.  shipped and delivered within about a week.
=> added sava instock site link

docs/guide/build_hardware.md
I bought mine on Amazon so I put the link in there as an option.
=> Added Amazon link for LiPo battery

docs/guide/build_hardware.md, docs/roll_your_own.md, docs/supported_cars.md
Adds Blaze and Short Course Truck
=> Documentation update to include new standard cars

donkeycar/management/base.py, donkeycar/parts/datastore.py
The error detail is
```
File "/home/pi/donkeycar/donkeycar/management/base.py", line 426, in execute_from_command_line
c.run(args[2:])
AttributeError: 'ShowPredictionPlots' object has no attribute 'run'
```
executing
`donkey tubplot /home/pi/d2/data/tub_1_18-01-02 --model=/home/pi/d2/models/mypilot
`
=> Fix an error when using the donkey tubplot command

.travis.yml
Makes use of TravisCI build stages. Note that this feature is still
in beta.
=> Deploy to pypi only once when using build matrix

donkeycar/util/web.py
=> support offline networks

donkeycar/parts/actuator.py, donkeycar/parts/camera.py, donkeycar/parts/clock.py, donkeycar/parts/datastore.py, donkeycar/parts/keras.py, donkeycar/parts/simulation.py, donkeycar/parts/transform.py, donkeycar/parts/web_controller/web.py
I have started building my own car. 
I would like to contribute to this great project.
As a start point, I fixed source code from parts directory to follow PEP8 specification:
https://www.python.org/dev/peps/pep-0008/
In my opinion it is improving consistency of the source code.
=> Fix source code of parts directory, to follow PEP8 rules

docs/README.md, docs/guide/build_hardware.md, docs/index.md, docs/legacy.md, docs/roll_your_own.md
Added a bunch of changes - Added new link for Donkeycar store, new plastics, added alternative designs to "roll your own page", updated trademark with registered trademark.
=> updates and corrections

donkeycar/parts/datastore.py, donkeycar/tests/test_tub.py
BUGFIX fixed get_record_gen when shuffle==False, added test
=> BUGFIX fixed get_record_gen when shuffle==False

docs/guide/build_hardware.md
This was not originally clear and I ended up attaching it upside down during my build.
=> Clarify top plate orientation to roll cage

donkeycar/parts/datastore.py
This is my first ever Pull requrest. Sorry if I'm not doing it right.
`record_dict` is referenced before it is defined. Unpacked the `iterrows()` tuple in the for loop to `_, row` and called `record_dict = self.read_record(row.to_dict())`
Cheers, Josh
=> Fix not defined error

scripts/remote_cam_view_tcp.py
Add script to allow remote cam viewing when images are published by donkeycar using TcpServer (set by "PUB_CAMERA_IMAGES = True" in config file in current codebase)
=> Add client script for when "PUB_CAMERA_IMAGES = True"

donkeycar/management/tub_web/base.html, donkeycar/management/tub_web/static/tub.js
+ If clip is playing then speed changes from dropdown take effect immediately.
+ Clicking an image in the clip timeline will jump to that frame.
=> Update tubclean webinterface

donkeycar/management/base.py, donkeycar/templates/complete.py
Ref issue #404 
* Fix tubplot to NOT provide its own default model type.
* Add the model type to the tubplot title.
=> Fix tubplot to NOT provide its own default model type.

donkeycar/management/base.py
Reintroduce the much improved Calibrate function that was in a previous codebase:
- Does not have 10-loop limit
- Provides interactive method to exit from utility.
=> Reintroduce the much improved Calibrate function

donkeycar/templates/train.py, donkeycar/tests/pytest.ini, donkeycar/tests/test_train.py
Tests and fixes related to issue #406
=> Fix training split (issue 406)

docs/parts/controllers.md, donkeycar/parts/controller.py
* This step helps discover mappings not already pre-existing and
provides a way to dicover and modify defaults.
* Adds Forza mode for the XboxOne controller.
=> Add axis names and button names to Joystick.

donkeycar/parts/keras.py, scripts/freeze_model.py
* Workaround for a bug when using `tensorflow-gpu` with `1.13.1`
* Adds support for freezing graphs and converting to `TensorRT` models.
=> Improvements to the ML Pipeline

donkeycar/config.py, donkeycar/parts/augment.py, donkeycar/parts/camera.py, donkeycar/parts/cv.py, donkeycar/parts/image.py, donkeycar/parts/keras.py, donkeycar/parts/tensorrt.py, donkeycar/templates/basic_web.py, donkeycar/templates/complete.py, donkeycar/templates/train.py, donkeycar/tests/test_train.py, donkeycar/utils.py
this creates a part to pre-process image before inference to apply crop, as well as normalize images. It also crops and normalizes during training.
=> crop and normalize outside of model

donkeycar/parts/tensorrt.py, scripts/freeze_model.py
* Reverse throttle and steering.
* Reduce the number of nodes in the frozen graph further.
Test: Tested with donkey tubplot.
=> Improvements to TensorRT Pipeline.

donkeycar/management/base.py
* Use index to correctly go from first to last frame
* Use index from tub instead of try/catching on continuous frames
* Use picture frame size to determine mid of and length of user / pilot line plots
* Remove unused code/variables
* Some pep-8 formatting
=> MakeMovie improvements:

donkeycar/management/base.py
Update MakeMovie to allow plotting of user data only (no model) - useful for determining quality of user input.
Also fix the confusing mix of model argument being None vs "None".
=> Update MakeMovie to allow plotting of user data only

donkeycar/parts/camera.py, donkeycar/utils.py, donkeycar/vehicle.py
Fix image handling (img_crop, normalize_and_crop, load_scaled_image_arr) to deal with greyscale images correctly.
Also various spelling fixes.
=> Fix greyscale image handling

docs/guide/robot_sbc/setup_jetson_nano.md
Simplifying cd to projects dir
=> add ~/ to "cd projects" command

docs/guide/robot_sbc/setup_raspberry_pi.md
Fix these typos: it's/its, you're/your, insterting/inserting
=> Fix typos in setup_raspberry_pi.md

donkeycar/utils.py, donkeycar/vehicle.py
Improve performance by replacing division /255 with multiplication and adding some pep-8 formatting. Also improving jitter output to be in ms.
=> Small performance improvement and jitter output in ms

docs/guide/build_hardware.md
Previous link is broken (404).
=> Fix broken link to "Roll Your Own" page

docs/guide/robot_sbc/setup_raspberry_pi.md
Docs still linked to Stretch, changed to link to buster.
=> 493 updated rpi install docs to use buster

docs/guide/robot_sbc/setup_jetson_nano.md
I kept getting a CMAKE error related to the location of the build directory. I was able to fix it as shown in the pull request.
=> fix cmake build directory error

docs/guide/create_application.md
=> updated to include basic Robo HAT MM1 instructions

docs/guide/robot_sbc/tensorrt_jetson_nano.md
Trail to make more clear documentation, fluent.
=> update tensorrt conversion (version 2)

docs/guide/train_autopilot.md
=> Update train_autopilot.md rsync command

donkeycar/parts/robohat.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
Linked with #576 .   No automatic way at the moment for picking the serial port when using USB_SERIAL for simulator control.  This will have to do.
=> Update comments for serial port.

donkeycar/contrib/robohat/code.py
Add some more variable customisation for Donkey Simulator and Robo HAT MM1
=> Update for Robo HAT MM1 code.py

donkeycar/parts/web_controller/web.py
Prevent the thread from crashing if websocket connection is closed.
=> Websocket client error handling

docs/guide/create_application.md
Added Hackster IO Links
Changed the link for the code.py to internal Donkey Car maintained version.
=> Updated Robo HAT MM1 instructions

scripts/profile.py
Fix image which was simply black after casting [0,1) values to int.
=> Fix image in FPS profiling script

donkeycar/parts/robohat.py, donkeycar/parts/web_controller/web.py, donkeycar/tests/test_robohat.py
Simpify pwm value logic and add additional checking for invalid value.
=> Mm1 pwm value check

donkeycar/templates/train.py
* Check point callback was initialised with on_best_model callback which overwrote the model on the end of each epoch, even when the valuation loss did not improve
* Fix passing on_best_model callback only if cfg.SEND_BEST_MODEL is set in the config
* Delete model.save() on_best_model as model saving is performed by Keras base class of MyCPCallback.
=> Fix train script to correctly save best valuation loss model

docs/guide/create_application.md
Added Hackster IO Links
Changed the link for the code.py to internal Donkey Car maintained version.
=> Updated Robo HAT MM1 instructions (Master PR)

docs/guide/create_application.md
* added more myconfig.py options
@nvtkaszpir
=> updated docs for robohatmm1

donkeycar/parts/datastore_v2.py
* Cache cumulative line lengths for `Seekable`s. This brings the new datastore on par with the legacy datastore on SSDs.
Test: Existing tests pass.
=> Speed up datastore_v2

docs/guide/robot_sbc/setup_jetson_nano.md
- Update tensorflow version to 1.15.0
- Add doc for Jetpack 4.4
- Remove opencv installation
=> Update Jetson nano doc

docs/guide/dataset_pretrained_models.md, mkdocs.yml
Initially I have included Tawn's dataset. Once we have more dataset, particularly with the dataset in simulator, we can make a pre-trained model available for download by others.
=> Add dataset and pre-trained model page

donkeycar/parts/web_controller/templates/wsTest.html, donkeycar/parts/web_controller/web.py
This fixes https://github.com/autorope/donkeycar/issues/634
Refer to https://github.com/tornadoweb/tornado/issues/2871 for how to solve this.
=> fix issue #634

donkeycar/templates/basic.py, donkeycar/templates/cfg_basic.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
Add auto-generated tub path to basic car template, otherwise the vari…able cfg.DATA_PATH will be used as is for the tub path.
=> Add auto-generated tub path to basic car template

setup.py
Added progress module to be installed.  Found it missing when running donkey createcar.
=> Update setup.py with progress module for pi

donkeycar/management/base.py, donkeycar/templates/complete.py
* Train still prompts you to move to then new entry point.
* Also fixes https://github.com/autorope/donkeycar/issues/655
=> Rename `drive.py` to `manage.py` to preserve CLI compat.

donkeycar/parts/datastore_v2.py
* Add __exit__ handlers again.
* Use `os.linesep` to deal with line separators consistently.
=> Minor datastore_v2 improvements.

donkeycar/parts/datastore_v2.py
=> Be explicit about newline characters #2

.travis.yml
* Add OSX into `install` and `test`
* Update Linux dist from 18.04 to 20.04
=> Integrate osx into travis.

donkeycar/templates/simulator.py
=> fix autorope/issue #671

donkeycar/parts/web_controller/templates/wsTest.html, donkeycar/parts/web_controller/web.py
See issue #634 .
Copied and pasted Jonathan's working files from the master branch and now pushing the changes into dev.
> Refer to tornadoweb/tornado#2871 for how to solve this.
=> Fix issue #634 on dev

donkeycar/parts/web_controller/web.py, donkeycar/templates/calibrate.py, donkeycar/templates/cfg_basic.py, donkeycar/templates/cfg_complete.py, donkeycar/tests/test_web_controller.py
This PR is same as https://github.com/autorope/donkeycar/pull/675 but for dev branch.
=> Allow overriding WEB_CONTROL_PORT from env variable

donkeycar/templates/basic.py, donkeycar/templates/cfg_basic.py
- Update cfg_basic.py with simulator parameters
=> Add simulator support to basic.py

install/envs/mac.yml
Fixing https://github.com/autorope/donkeycar/issues/686
=> fix h5py version for mac

donkeycar/parts/datastore_v2.py, donkeycar/tests/test_datastore_v2.py
* This makes reading a 100x faster.
=> Switch to using memory-mapped files when reading.

donkeycar/tests/test_telemetry.py
* Disable until we can fix that.
=> The telemetry mqtt test is breaking w/ a timeout on the connection to the server

donkeycar/parts/tensorrt.py
Correcting wrong attempt in PR #698.
=> Need to implement `inference()` and not `run()` in TensorRT 

docs/dev_guide/model.md, docs/utility/donkey.md, mkdocs.yml
* Adding new page with detailed info how to create own models
* Update donkey command section with `donkey train` command.
=> * Update doc with developer section for creating own models

docs/guide/dataset_pretrained_models.md, mkdocs.yml, setup.py
* Prep for making `4.x` official.
=> Merge Changes from `master` to `dev`. 

docs/guide/robot_sbc/intel_t265.md, donkeycar/parts/controller.py, donkeycar/templates/cfg_path_follow.py, donkeycar/templates/path_follow.py
Properly rebased on Master this time, I hope
=> Updated path follower with Intel T265

donkeycar/templates/cfg_basic.py
=> Add missing AI_THROTTLE_MULT - address #736

donkeycar/parts/keras.py
This is copied from v3. We had this plot before.
=> Add back training history plot

donkeycar/templates/cfg_basic.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/cfg_cv_control.py, scripts/multi_train.py
I just replaced every instance of "donkey-mountain-track-v0" to "donkey-generated-track-v0"
for more info: https://github.com/autorope/donkeycar/issues/759
=> myconfig.py default scene name fix

donkeycar/templates/cfg_complete.py
=> Reverting JOYSTICK_THROTTLE_DIR to v3 default

docs/parts/about.md
Derived from Tawn Kramer's excellent video
https://www.youtube.com/watch?v=YZ4ESrtfShs
=> Make clear how to call "run" vs "run_threaded"

donkeycar/parts/dgym.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
This PR needs the PR sent to https://github.com/tawnkramer/gym-donkeycar to work.
code based on original version by PaulH, adapted and extended by Rainer Bareiss
2021, Team Parking Lot Nerds
=> feat: enables to store position, gyro, accel, vel of simulator car in tub files

docs/guide/robot_sbc/setup_raspberry_pi.md
This went accidentally wrong in #777 - sorry.
=> Fix tf 2.2.0 install on RPi in doc.

docs/parts/path_following.md, donkeycar/templates/cfg_path_follow.py, donkeycar/templates/path_follow.py
Addresses comments in this issue:
https://github.com/autorope/donkeycar/commit/0b64ff4c4f8fda2659bef2cc7a744f9f5b7cfdbe#commitcomment-45892582
=> Updated Path Follower instructions

.github/linters/.python-black, .github/workflows/push-docs.yml, .github/workflows/python-package-conda.yml, .github/workflows/superlinter.yml, docs/faq.md
Adding GitHub Action that automatically pushes docs to `docs.donkeycar.com` when the content of the `docs/` folder changes.
=> Add automatic pushing of docs

donkeycar/templates/cfg_complete.py
Again, apologies to everyone whose installation has been failing. Blame Travis!
=> Added "DRIVE_TRAIN" back to compete template, too

.github/linters/.python-black, .github/workflows/push-docs.yml, .github/workflows/python-package-conda.yml, .github/workflows/superlinter.yml, README.md, docs/faq.md, docs/guide/robot_sbc/intel_t265.md, docs/guide/train_autopilot.md, docs/parts/about.md, donkeycar/parts/controller.py, donkeycar/templates/cfg_complete.py
Created a merge PR with recent changes on master back to dev. This contains:
*  the changes to GitHub Action files
*  updates to docs and readme files
*  one very recent fix to the config
=> Merge master to dev

donkeycar/parts/pytorch/ResNet18.py, donkeycar/parts/pytorch/torch_data.py
This resolves the issue @DocGarbanzo mentioned to me about PyTorch tests failing. All tests now pass.
The issue was caused when upgrading PyTorch Lightning from 1.1.0 to 1.2.4 when additional value checks were added in.
=> Fix pytorch lightning error

donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
adding logic to control the motors with a L298N
using the enable pins for pwm
=> adding support for L298N motor controller

docs/guide/simulator.md
Updated the sim API in the doc,
more coming in the future
=> Some changes in the docs regarding the Sim API

donkeycar/parts/dgym.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
added support for virtual lidar
Related to this: https://github.com/tawnkramer/gym-donkeycar/pull/66
=> Virtual lidar support

donkeycar/templates/cfg_complete.py
=> Fixed cosmetic typos

donkeycar/templates/complete.py
As suggested by @DocGarbanzo. It works!
=> Added "__name__" to logger to avoid double reporting

donkeycar/parts/keras.py
Located origin of currently slow performance of h5 models, which is due to using `model.predict(...)` instead of the callable interface `model(...)` for inferencing. Updating to callable inferencing brings back performance on RPi 4 to ~22fps.
=> Fix for current slow performance of h5 models on RPi.

donkeycar/__init__.py, donkeycar/pipeline/database.py, donkeycar/pipeline/training.py, setup.py
* Revert to passing full path to model in training call which got accidentally broken in 4.2 master.
* Bump version to 4.2.1
=> Merge PR #873 to master

donkeycar/parts/oled.py
Just cosmetic. Tested and works
=> Eliminate unnecessary spaces messing up OLED display

donkeycar/parts/tfmini.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py, setup.py
Works with [TFMini](https://www.sparkfun.com/products/retired/14588) and [TFMini Plus](https://www.sparkfun.com/products/15179). Tested on Raspberry Pi. 
Let me know if anything should be added/changed.
=> Add support for TFMini Lidar

setup.py
=> version="4.3.25"

donkeycar/parts/pytorch/ResNet18.py, donkeycar/parts/pytorch/torch_train.py, donkeycar/tests/test_torch.py, install/envs/mac.yml, install/envs/ubuntu.yml, install/envs/windows.yml, setup.py
* A couple of changes in the Trainer and the model summary
* Updated the yaml files to remove pytorch versions, but fix torchvision to avoid https://github.com/pytorch/pytorch/issues/42078
* Bumped version
=> Upgrade to newest version of pytorch

donkeycar/parts/dgym.py
Fixes https://github.com/autorope/donkeycar/issues/1086
=> Fixing initialization of self.info

README.md
Update and reorganize the readme with a lot more explanation of Donkeycar and links to key parts of the documentation.  It also includes some helpful links out to resources that will help a new user be prepared for Donkeycar.
=> Update github README.md with more detail and links to docs

donkeycar/__init__.py, donkeycar/pipeline/augmentations.py, donkeycar/tests/pytest.ini, donkeycar/tests/test_train.py
The albumentations package has an updated structure and changed interfaces slightly. We are updating our donkey code accordingly. Also adding some improvements for our test, allowing reruns for the flaky web socket test and a proper tub clean up in the train test.
=> Update to new albumentations 
