autorope/donkeycar

donkey/remotes.py, donkey/templates/session.html, donkey/templates/static/style.css
@wroscoe I added back the click-to-drag multiselect capabilty with some filters that make it more performant. This feels pretty snappy on my computer for session pages with up to 500 images. Beyond that it lags pretty badly, so I updated the pagination code to break the pages at 500 instead of 1000.
Also adds iconography to indicate turn direction (requested by @adammconway).
=> Draggable multiselect and turn icons

donkey/templates/static/main.js, donkey/templates/vehicle.html
- Add control mode toggle for gamepad (disabled when no gamepad present)
- Gamepad throttle respects max throttle setting
- Disable joystick loop when in gamepad mode to prevent conflicting control inputs (and vice-versa)
- Add modal explaining control modes (accessed by clicking on the Control Modes form label)
=> Gamepad toggle

config/vehicle.ini, donkey/templates/static/main.js, donkey/templates/vehicle.html, scripts/simulate.py
- To use constant throttle, you must select a max throttle value (constant throttle will use this max value as the throttle)
- Also fixes a variable type problem for the max throttle setting (now properly converts to the string value from the form to the float value expected by the server)
- Also replaces the user-specific model path in `simulate.py` with a more general path to the default model
- Corrects the steering PWM settings in the default vehicle.ini to match the Magnet.
=> Add constant throttle option

scripts/drive.py
When starting the drive script, you must specify a remote url or ip, along with the protocol and port number. I've added some simple protections to help protect users who might make a mistake. 
There are some negligible differences in whitespace that you can cherry pick around, only the block of text between 32-38 is important.
=> Add protections to the remote url

donkeycar/parts/controllers/joystick.py
Recording is manually toggled in this version. Additional controls added:
button map name => PS3 button => function
* top2 = PS3 dpad up => increase throttle scale
* base = PS3 dpad down => decrease throttle scale
* base2 = PS3 dpad left => increase steering scale 
* pinkie = PS3 dpad right => decrease steering scale
* trigger = PS3 select => switch modes
* top = PS3 start => toggle constant throttle
* circle = PS3 circrle => toggle recording
* triangle = PS3 triangle => increase max throttle
* cross = PS3 cross => decrease max throttle
=> Add more button controls for PS3 controller

donkeycar/parts/stores/tub.py, donkeycar/templates/donkey2.py
This is to fix a nasty bug that prevented training from moving beyond the 1st tub. It was probably the reason why your model didn't work @wroscoe, and none of the Donkey cars did well Saturday. I feel so bad about it!
Also this fix would require everyone to regenerate manage.py.
One drawback of this implementation is that up to batch_size records in each tub may not be used at all. This is because now `get_record` will throw `StopIteration` exception when there aren't enough records to fill a whole batch so that `itertools.chain` can move on to next tub.
=> Nasty bug in multi-tub training

docs/guide/install_software.md
If the terminal or editor supports pasting unicode, it'll look alright, but not parse and the car won't join the network.
=> Fixed quotes in documentation

donkeycar/parts/__init__.py, donkeycar/parts/stores/tub.py, donkeycar/templates/donkey2.py
Currently the dataset returned from generators will be cached by `itertools.cycle` after 1st epoch. This becomes a problem when I want to use data augmentation to generate unlimited amount of data.
This PR fixes the issue stated above.
=> Prevent the generators from being cached

docs/guide/simulator.md
I had some issues generating logs when running the simulator locally. I checked
/Users/<username>/Library/Logs/Unity/Player.log
and found the following
`
UnauthorizedAccessException: Access to the path "/private/var/folders/.../d/donkey_sim.app/log/log_car_controls.txt" is denied.
`
This is caused by Sierra's sandboxing of untrusted applications, and will probably be an issue for all Mac users.
=> Extra steps for Mac installation of simulator

docs/guide/install_software.md
Added lines 227 to 231 to remind folk to install gcc / Apple's Command Line for Tools for Xcode if user hasn't either installed.
=> Add 'xcode-select --install' to ## install on Mac

docs/guide/install_software.md
Using underscore in the host name prevents you from pinging the Pi. 
According to RFC1123, section 2.1 "Host Names and Numbers" host names are limited to just letters, digits, and hyphens.
=> No underscores in host name

docs/guide/build_hardware.md
Due to screw head size and placement, using top screw holes on Pi cam can cause a short. Using bottom two holes avoids this potential issue.
Reported by @Ezward on the Donkey Car Slack: ﻿https://donkeycar.slack.com/archives/C487786DC/p1522638679000068?thread_ts=1522442985.000360&cid=C487786DC
=> Screw location for Pi cam can result in short

donkeycar/parts/datastore.py
Open for suggestions and opinions. I've tested this change with my tubs and got similar results.
Before this change dataset was shuffled once and
then on every step random sample was returned.
Problem is that this way we do not guarantee that
all samples from dataset will be used.
=> Disable additional shuffling while training

docs/guide/install_software.md, setup.py
Assume a compatible flavor of the tensorflow library is
pre-installed. This allows Donkey to be installed on systems
where tensorflow-gpu is installed w.o. having to fiddle with
dependencies.
Since all install instructions in Donkey docs pre-installs
tensorflow already, this is a minor change.
=> Remove TensorFlow dependency

docs/guide/calibrate.md
1. ` and ' typo.
2. Mkdocs needs an emtpy line before the itemization.
-- Sorry for this trivial change.
=> m: Fix Markdown for MkDocs

docs/guide/simulator.md
Why I write it on the simulator docs?
- 2 month ago I wanted to install the donkey car on my machine, but I use Manjaro (arch) distribution Linux and when I saw the only Ubuntu(Debian) option, I decided don't try install it by doc download link, i search by the source code and try build it on my arch Linux, but it spent so much time, so I tried download it to verify what's the simulator extension, and it was a binary! Because the docs said that release is built to Ubuntu(Debian) I thought it was a .deb file, but it isn't, its was a binary file! if I knew it was a binary file I already tried run it on my machine before, and it doesn't was written on docs.
=> [DOC] explanation about others Linux distributions installation 

docs/guide/install_software.md
If you have tensorflow package installed, it apparently uses the CPU even if you have tensorflow-gpu and a properly set up GPU. I fixed this by uninstalling the tensorflow package manually using pip, but it would have been nice to realize this earlier.
=> Make tensorflow/tensorflow-gpu install clearer

docs/supported_cars.md
Alternative would be to rename the asset Latrax.JPG to Latrax.jpg
=> Fixed link to photo of Latrax -- case sensitive

donkeycar/parts/web_controller/web.py
Fixed camera streaming for Firefox (65.0.1)
**Trigger**
streaming from raspberry camera doesn't work in firefox
**changes**
Added `\n` to `boundarydonotcross` header for each frame. Now it works for both chrome and firefox
@wroscoe @scitronboy
=> Fixed camera streaming for firefox

donkeycar/parts/actuator.py
The ESC "Tamiya TBLE-02" makes a little leap otherwise.
This leap does not happen at the first time after power on,
but on all subsequent starts of the Donkeycar driving program.
=> Wait 0.1s after initializing the PWM controller.

docs/parts/controllers.md, donkeycar/parts/controller.py, donkeycar/templates/cfg_complete.py
Fix for issue where the xbox controller throttle input is backwards; so pulling joystick down goes forward, pushing up goes backward.  
- added JOYSTICK_THROTTLE_DIR to config; maintained -1.0 default.
- updated controller.py get_js_controller() to pass throttle_dir using cfg.JOYSTICK_THROTTLE_DIR
So now the user can add JOYSTICK_THROTTLE_DIR = 1.0  to their myconfig.py in order to flip the throttle input on their on their controller.
=> XBox controller has throttle reversed, so added throttle_dir config

donkeycar/management/base.py
Fix "salient" operation by adding tensorflow.python prefix to "keras" imports.
Fix "ShowCnnActivations" by adding tensorflow.python prefix to "keras" imports.
=> Adding tensorflow.python prefix to "keras" imports where required

docs/guide/create_application.md, donkeycar/parts/camera.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
If the Jetson Nano's camera is mounted in a rotated position, provide an option
to flip the camera frame.
CSICamera nano part is implemented using gstreamer. Passing
the flip parameter to the gstreamer pipeline will do this.
Signed-off-by: Jithu Joseph <jithu83@gmail.com>
=> CSI camera: Config option to flip the cam frame orientation

docs/guide/robot_sbc/setup_jetson_nano.md
At lines 103-104 the mv command removes the version IDs from the directory names for opencv and opencv_contrib.  This change makes the cmake command starting on line 123 consistent with these directory names.
=> Update setup_jetson_nano.md docs with the correct unversioned directory names

donkeycar/parts/keras.py, donkeycar/parts/tensorrt.py, donkeycar/templates/complete.py, donkeycar/utils.py, scripts/freeze_model.py
* This PR adds support for Tensor RT.
* There are probably more minor improvements I can make to `tensorrt.py`, but I think this is a good starting point.
* `freeze_model.py` exports metadata about the model which helps us reconstruct the TensorRT model.
* Make sure `pycuda.autoinit` is never loaded during training, as it interferes with `tensorflow-gpu`.
Test: Tested this on my Jetson Nano.
----
* **Note** - This PR removes a `Cropping2D` layer from the linear model as its unsupported by the TensorRT runtime. If you are using Cropping2D use `opencv` to do the cropping as a pre-processing step.
----
Follow the instructions [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html#installing-tar). Make sure you use the `tar` file instructions unless you have …
=> Support for TensorRTLinear model.

donkeycar/parts/tensorrt.py
@tikurahul actually figured this out - I'm just stealing his thunder.
https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/parsers/Uff/pyUff.html
=> Pass input shape args in the right order

donkeycar/vehicle.py
Fix PartProfiler to take KeyboardInterrupts into account as well as initialisations of parts. It seems like on_part_finished() is not called when a KeyboardInterrupt occurs leaving the time value in the time difference which messes up the timing table max and avg values. Here, we simply chop off first and last entry form the timing arrays. We also add a median to the table to see if the distribution of timings is skewed.
=> Fix PartProfiler showing wrong number for KerasLinear

donkeycar/management/base.py, donkeycar/parts/actuator.py
Allow PWM freq. of PCA9685 to be specified (default value remains as before)
Also includes code to scale PWM values appropriately based on the freq. specified.
=> Allow PWM freq. of PCA9685 to be specified

donkeycar/parts/controller.py
Previously while driving, if the throttle scaling was changed, the throttle would need to be released, then applied again in order for the new scaling to be used.  This small modification allows scaling to be changed while driving so maximum speed can be slightly increased/decreased on the fly.
Removed some extra spaces in the code and made the layout of the spacing a bit more consistent.
=> Enable throttle scaling while controlling manual throttle

donkeycar/tests/test_vehicle.py
Newer versions of pytest require replacing the `message` parameter in pytest.raises() with a pytest.fail() at the end of the `with` statement:
def test_should_raise_assertion_on_non_list_inputs_for_add_part():
vehicle = dk.Vehicle()
inputs = 'any'
>       with pytest.raises(AssertionError, message="inputs is not a list: %r" % inputs):
E       pytest.PytestDeprecationWarning: The 'message' parameter is deprecated.
E       (did you mean to use `match='some regex'` to check the exception message?)
E       Please see:
E         https://docs.pytest.org/en/4.6-maintenance/deprecations.html#message-parameter-of-pytest-raises
=> Remove deprecated message argument from pytest.raises().

docs/guide/calibrate.md, donkeycar/templates/basic_web.py, donkeycar/templates/complete.py
When you put in the Browser the ip-Adress with :8887 its not running.
You must put the hostname.local:8887
Test it with Ubuntu 18 and Firefox
=> Update Ip-Adress change to Hostname

donkeycar/parts/keras.py
The fix for TensorFlow 1.3.1 introduced in https://github.com/autorope/donkeycar/commit/d1448d8e1cf5148a51853fe282978664db0deacb does not work for TensorFlow 1.4 and higher. Rather than having to remove these lines when trying out a new TensorFlow version, these lines are only executed if TensorFlow 1.3.1 is being used.
=> check TensorFlow version before overriding keras session

donkeycar/templates/train.py
Custom format for the figure/plot generated after training. Vector graphics might be preferred when presenting the results. The default format is still 'png'.
=> add arg for custom figure format (e.g. 'png', 'pdf', 'svg' ...) for train.py

donkeycar/parts/actuator.py
Using the Teensy PCA9685 emulation I ran across a few I/O errors when donkey tried to set a new pwm value. It was explained by the original author of the emulation that the rPi I2C library doesn't "doesn't allow slaves to clock extend" which seems to be something lots of I2C slave devices do. I found that a simple retry of the message was enough to cover the sporadic I/O errors I'd seen.
=> retry of pwm.set_pwm on first exception due to I2C timing errors

docs/guide/create_application.md
The previous page of instructions could mostly be copied and pasted into terminal and would work. This small change allows that to continue for this line.
=> Documentation: Editing myconfig.py without changing directory

.gitignore, .markdownlint.yaml, .travis.yml, .yamllint
* Add stages for makrdownlint, yamllint, mkdocs
* Update travis config so that it no longer generates warnings if pasted
into https://config.travis-ci.com/explore
* Speed up linting phase (skip install)
* Move docs build earlier
* Allow yamllint and makrdownlint to fail
* Fix code coverage reports
=> Travis update

donkeycar/parts/actuator.py, donkeycar/templates/complete.py
- PWM actuators, i.e. PWMThrottle and PWMSteering each are taking up 2-3ms in the vehicle loop, that is 5-6ms in aggregate.
- If we want to run the car at 40 Hz than we only have 25ms per loop for all parts. Keras takes up 13-15ms, so optimising the other parts to a minimum will leave more cpu time for the auto pilot.
- In recording drive mode, TubWriter seems to be taking up most of the time, around 7ms.
- Change of PWMSteering and 'PWMThrottle` into threaded parts. Non-threaded functionality is maintained.
- Minor code changes (pep-8), mostly whitespace
- Actuator performance goes down to < 0.1 ms.
=> Performance improvement of PWMThrottle and PWMSteering 

donkeycar/vehicle.py
Adding more percentiles to help investigating if slower parts are frequently slow or only in rare occurrences.
- Part profiler shows min, max, average and 50% percentile (= median)
- Add 90%, 99% and 99.9%
=> Small change - added 90, 99, 99.9 percentiles to performance statistics.

donkeycar/parts/actuator.py, donkeycar/utils.py
map_frange() was defined in actuator.py and called in actuator.py by RPi_GPIO_Servo class.  It was defined with a 'self' argument, as if it was a class method, but it was defined in the module scope.  It's a useful function, so I moved it to utils.py and changed actuator.py to import it.
=> removed self arg from map_frange and moved map_frange to utils

donkeycar/templates/basic_web.py, donkeycar/templates/complete.py
Addresses issue 448 https://github.com/autorope/donkeycar/issues/448
Sometimes throttle or steering values can become null if the drive mode is changed.  This code protects against None type inside of DriveMode class.
=> 448 protected DriveMode from None throttle or steering

donkeycar/parts/tflite.py
tf version 2 does not have the from_keras_model_file function so it must be explicitly loaded and the converter object created.
=> add support for tf version 2

donkeycar/parts/oled.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py, setup.py
* Connect the PiOLED display over I2C, and configure the bus number.
* Change `myconfig.py` to update the bus number, and the display automatically shows useful information.
* Uses the `Adafruit_SSD1306` library.
=> Add support for a PiOLED display to show useful information.

docs/guide/robot_sbc/setup_jetson_nano.md
* Updated filepath
* Added Numpy install command (pip install numpy failed, apt-get worked)
* Added hyperlink to skip to next section
* Moved common swap space instructions to the beginning of the section
* Punctuation
=> Updated precompiled cv2 instruction for JetPack 4.3

donkeycar/parts/controller.py
XboxOneSwappedJoystickController calls the init method from XboxOneJoystickController which initializes controller with steering on left and throttle on right. Then it just adds additional mapping to make steering on right and throttle on left, without clearing prior mapping.
This ends in both joysticks to react to steering **and** throttle in the same time, which renders the whole control process unusable - unless you focus on steering with single joystick or you are super precise with your fingers ;-).
This PR adds required additional mapping to the old axes so that they do nothing - so that they do not react any longer to the input, which effectively makes joystick swap as intended.
=> Fix issues with xboxswapped controller

donkeycar/parts/datastore.py, donkeycar/parts/realsense435i.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py, donkeycar/vehicle.py
- enabled using CAMERA_TYPE = 'D435'
- supports RGB, DEPTH and IMU output; each of which can be individually toggled with configuration REALSENSE_D435_xxxx
- supports addressing a camera with a specific ID in the case of multiple cameras (or in presense of T265)
- IMU output is compatible with MPU6050 and IMU model. (Not tested.)
- depth is output as a separate, aligned image in 16bit grayscale png format.  So pixels in depth image can be queried to find the depth of a pixel in the RGB image.
=> Support for Realsense D435 and D435i depth cameras

docs/parts/imu.md, donkeycar/parts/imu.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
This MR adds support for MPU9250 (#549). 
To configure an mpu9250 just enable 
` HAVE_IMU = True` 
and set 
`IMU_SENSOR = 'mpu9250'`
=> Add support for MPU9250

donkeycar/parts/web_controller/templates/base_fpv.html, donkeycar/templates/complete.py
1. Fallback USE_FPV to use 'cam/image_array' as inf_input is normalized.
2. The video stream should fit the screen by height instead of width
Note: By using 'cam/image_array' , crop (if set) is not shown in the FPV. Just aim to fix the FPV at the moment as it is a bit tricky to incorporate the crop in the current codebase. Welcome any feedback. Thanks.
=> Fix USE_FPV

donkeycar/parts/web_controller/templates/base.html
As per this issue: https://github.com/tawnkramer/gym-donkeycar/issues/23
Fixes the UI controller for Windows when running the car in 'traditional' mode.   Google Chrome rejects the files due to this parameter.  Setting it to blank fixes the error.
=> removed incorrect hashes as per issue 23 in gym-donkeycar

donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
ImageListCamera is really handy for local development. It was there before and I guess it was removed unintentionally.
=> Add back ImageListCamera support 

donkeycar/management/base.py
I think,  tubplot option in management/base.py is mistaking.
--tub is only one. I changed help message.
--limit is integer. I add type=int.
=> tubplot option fix

.travis.yml, setup.py
Raspbian Buster is using Python 3.7. Previous OS Stretch was on Python 3.5 which now seems outdated. Raspberry Pi4 are coming with Buster but RPi 3 users should upgrade their OS. For compatibility to older Python installations on the PC version 3.6 is kept.
=> Restrict support to python 3.6 and 3.7

docs/utility/donkey.md, donkeycar/management/base.py, donkeycar/parts/augment.py, donkeycar/parts/datastore.py, donkeycar/tests/test_tub.py
The data augmentation can be enabled in training by passing the `--aug` flag. However, this setting slows down training by a bit, in particular if the tub contains > 100k records. This change contains the following:
* Adding a new member function to the `Tub` through which augmentation can be performed on the  images in place
* Adding a new donkey command `donkey tubaugment` to call the above function with the option `--inplace`. If omitted a new tub is created instead of the manipulation of the existing images.
* There is a small refactoring in `augment.py` to decouple the image transformation from numpy arrays to PIL and back. Also the color scaling has been increased from[0.0, 1.0] to [0.0, 2.0].
* Adding the new command `donkey tubaugment` to the docs
* Small bits of pep-8 …
=> Allow data augmentation on tub outside of training

donkeycar/contrib/robohat/code.py
Tested.  Upload this code to Robo HAT MM1 and set `USB_SERIAL = True` if you want to use your RC Controller through Robo HAT MM1.
=> Add simulator over USB commands

donkeycar/management/base.py, donkeycar/parts/web_controller/templates/calibrate.html, donkeycar/parts/web_controller/web.py, donkeycar/templates/calibrate.py, donkeycar/tests/test_web_socket.py
Allow user to change config value such as STEERING_LEFT_PWM or MM1_STEERING_MID without restarting the car or running donkey calibrate command. I have added the following:
1. A much simplified verison of manage.py called "calibrate.py" to wire up the drive train to the web controller without changing manage.py. It will be created when user run createapp 
2. A /calibrate web page to perform the calibration
3. A websocket endpoint /wsCalibrate to support calibration message from mobile app and web page 
Currently the real-time calibration support PCA9685 and MM1 only.
=> Add real-time calibration 

donkeycar/management/base.py, donkeycar/management/makemovie.py
1. Make model type optional in makemovie. If model type is not provided, use config file
2. If salient is true, check whether model type is linear or categorical. If not, exit and warn user.
=> Make model type optional in makemovie and check model type if salient is true

docs/guide/robot_sbc/setup_jetson_nano.md
Recent versions of Jetpack (4.2+) include OpenCV precompiled w/GStreamer support via `libopencv` & `libopencv-python` packages. 
Installing `python3-opencv` installs an older version of OpenCV (via depends `libopencv-core3.2`) that was not compiled w/GStreamer support and points the python env to use it, breaking Donkeycar.
Besides this, Nano install docs worked at the time of writing.
=> Update nano install docs - python3-opencv vs libopencv-python

README.md
We no longer use the Slack channel for Donkey.
=> change slack to discord on readme

docs/guide/host_pc/setup_windows.md
Added more options for Installing Donkey Car on Windows.  
- Anaconda
- Native
- Windows Subsystem for Linux (WSL) - experiential
These options give more flexibility and could make deployment easier for some individuals.  I personally always install donkey car natively onto Python installed on the System.  I will be looking more into WSL going forward as it has some interesting benefits.
=> Windows Doc Updates

donkeycar/management/base.py, donkeycar/management/makemovie.py
add in --user flag for MakeMovie so that you can select if you want to draw the line on the video or not.  default: true
**Details**
Command works exactly the same except now you can add a --user flag to advise the donkey makemovie command that you don't want the user input shown.  The reason for this is that if you draw the green line for the user input from collected data, you cannot use the video for OpenCV or object classification because it throws out the algorithms (a random green line goes across everything).  So the solution is to still compile the video - but leave off the green line.
**Usage**
```bash
donkey makemovie --tub=data/latest --scale=1 --user False --out latest.mp4
```
... will output a video without the green line.
```bash
donkey makemovie --tub=data/latest --scale=1 …
```
=> MakeMovie Utility Update - option for turning off line drawing

donkeycar/parts/dgym.py, donkeycar/templates/cfg_simulator.py, donkeycar/templates/simulator.py
added in brake functionality for simulator only
**Updates**
- changed `dgym.py` file
- added new simulator.py template and configuration to keep other ones untouched.
- retains backwards compatibility with complete.py and other templates that have the simulator.
- doesn't interfere with training / data collection.
**Background**
This is to allow custom object and sign detection to stop the car effectively in the simulator (see _StopSignDetector_).   At the moment, the only way to control the car is via throttle.  To stop the car in the simulator (with it's low friction) you have to send very high reverse throttle values.  This leads to the car bouncing / rolling and not really being able to come to a complete stop.  With this update, brakes can be deployed and allow the algorithm to stop …
=> USYD Brakes - Simulator

donkeycar/templates/basic.py
Docopt throws a usage error as template gets renamed to manage.py and not drive.py
=> Fix template docopt, as it's called managed.py and not drive.py

donkeycar/parts/web_controller/web.py, donkeycar/templates/basic_web.py, donkeycar/templates/calibrate.py, donkeycar/templates/cfg_complete.py, donkeycar/tests/test_web_controller.py
To test this:
```
export WEB_CONTROL_PORT=12345
python manage.py drive
```
Visit `http://localhost:12345/drive` instead of `http://localhost:8887/drive`
Web Controller should start listening on port 12345. Port 8887 should not work after you specify the port in the env variable.
=> Allow overriding WEB_CONTROL_PORT from env variable

donkeycar/pipeline/__init__.py, donkeycar/pipeline/sequence.py, donkeycar/pipeline/types.py, donkeycar/templates/train.py, donkeycar/tests/test_pipeline.py, setup.py
* We start off with a list of shallow records, because it makes
things easier with a train_test_split.
* The rest of the pipeline is lazy.
* The `pipeline` module is typed.
=> A configurable training pipeline.

docs/dev_guide/model.md, docs/utility/donkey.md, donkeycar/__init__.py, donkeycar/parts/keras.py, donkeycar/pipeline/sequence.py, donkeycar/pipeline/training.py, donkeycar/pipeline/types.py, donkeycar/tests/test_pipeline.py, donkeycar/tests/test_train.py, donkeycar/utils.py, install/envs/mac.yml, install/envs/ubuntu.yml, mkdocs.yml, setup.py
* Add support for multi-dimensional model input by using dictionaries for tf data inputs
* Symmetric behaviour for `X, Y` data input model  - converting from tub record into numpy arrays and then into dictionaries.
* Simplify model interface by implementing output_types() directly in the base class using output_shapes() dictionary.
* Adding developer guide for own model development.
* Updated donkey command documentation with `train` command.
* Improve asserts and type hints in keras.py
* Added missing __init__.py in parts module.
* Add cool ascii text for donkey init and update yml and setup files including mypy.
* Remove model training test from Travis and change the test to relative convergence. This avoids random fall overs in CI.
* Added test of tf.data as used in the training …
=> Add support for models with multiple inputs and provide developer guide for model building

docs/dev_guide/model.md, docs/utility/donkey.md, donkeycar/parts/tub_v2.py, scripts/convert_to_tub_v2.py
* Update conversion script to translate discontinuous data.
* In developer guide add disclaimer for version and correct intra-page links.
=> Minor changes for 4.1 in tub conversion script and developer doc

docs/guide/host_pc/setup_windows.md
There is a small typo in docs/guide/host_pc/setup_windows.md.
Should read `unfamiliar` rather than `unfarmilar`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, unfarmilar -> unfamiliar

install/envs/mac.yml, install/envs/ubuntu.yml
Updated yaml files for conda envs to allow tf versions >= 2.2.0 <= 2.3.2. I checked that training w/ 2.3.2 and inferencing w/ 2.2.0 works w/o problems. However training w/ 2.4.0 seems to be not backward compatible to 2.2.x / 2.3.x, hence we keep the highest version at 2.3.2.
=> Add support for TensorFlow >= 2.2.0 <= 2.3.2 in conda env 

donkeycar/management/base.py
As agreed with @DocGarbanzo in this [PR](https://github.com/autorope/donkeycar/pull/712) I'm moving it to 1 commit to dev branch.
_FindCar donkey function will now work with Raspberries model 4 too, whose MAC addresses are different._
=> Fixed FindCar function for RPi4

install/envs/mac.yml, install/envs/pc.yml, setup.py
This solves the issue of getting error: `W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.` - this seems to occur for all versions >= 2.3.0.
=> Pin tf to 2.2.0 in setup for pip and yaml for conda.

install/envs/mac.yml
Fixed accidental `=` through `==` in pip section of conda yaml.
=> Patch to #752 - fix wrong operator in pip.

donkeycar/parts/perfmon.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py, install/envs/mac.yml, install/envs/pc.yml, setup.py
Performance monitor allows monitoring CPU / Memory and real Donkey execution frequency. I noticed that my own execution loop is considerably lower than 20Hz on Jetson Nano (~8Hz) and decided to measure it. On PC  simulator everything runs at 20hz as required.
This pull request includes performance monitor together with MQTT telemetry from another pull request (https://github.com/autorope/donkeycar/pull/688).
=> Add performance monitor

donkeycar/parts/tflite.py
Please suggest if there is a better place to put this fix. (Original `input_data` contains `float64` values, while tflite requires `float32`)
=> Fix tf2 lite nano camera support

donkeycar/templates/cfg_complete.py
This is the default in v3. Setting this to `True` by default will not activate the web controller and caused some confusion to users.
=> Set USE_JOYSTICK_AS_DEFAULT to False in cfg_complete.py

scripts/freeze_model.py
According to donkey car docs, we're now using tensorflow 2.2. The freeze_model.py script will throw exceptions on host Linux PC complaining about `tf.keras.backend.get_session()` isn't available and input/output node mismatch.
This fix solves the issue under tensorflow 2.2. 
NOTE: Although if the user wants to proceed to convert to TensorRT format he will probably encounter another issue. I'll describe the issue in a separate thread.
=> Fix for freeze_model.py (TensorRT)

docs/guide/robot_sbc/setup_raspberry_pi.md
Inferencing shows as about 6x slower on h5 files using tf 2.3.1 on RPi instead of tf 2.2.0. Updated install instructions.
=> Change RPi installation instructions from tf 2.3.1 to tf 2.2.0 

donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py, donkeycar/vehicle.py
The idea is to convert all "prints" into standard Python logging (which by default will look like "prints" in console but can be customized via config) and also sent to MQTT monitoring app.
This is a preliminary PR for review only.
Things to do:
* Convert all "prints" to `logger.info(`
=> new: convert prints to python logging

.travis.yml
Markdown lint seems to be producing unfavourable results in Travis, so we are disabling this here.
=> Remove markdown lint from travis.

donkeycar/tests/test_torch.py
We wanted to suppress all training tests in the CI - this one was forgotten.
=> Suppress pytorch training test on Travis

.github/workflows/python-package-conda.yml, .github/workflows/superlinter.yml
Small improvements for GH actions:
* Don't flag linter errors
* Add linter trigger on PRs
* Don't stop build on other platforms if one platform fails
* Don't trigger build if only changes are in `docs/`
=> Improvements in GitHub Actions

docs/guide/host_pc/setup_ubuntu.md
conda env create -f install/envs/ubuntu.yml
The error is visible on this website https://docs.donkeycar.com/guide/host_pc/setup_ubuntu/
link to modified file in your repo
https://github.com/autorope/donkeycar/blob/dev/install/envs/pc.yml
Thx for the open source sim
=> Documentation innacuracy ubuntu.yml was renamed pc.yml

docs/guide/host_pc/setup_windows.md
Conda says not to put "--user" in yml scripts so we'll have the users do this manually until we get to the bottom of the TF 2.2 installation errors on Windows
=> Added manual installation of Tensorflow with --user flag

donkeycar/parts/web_controller/templates/vehicle.html, donkeycar/templates/complete.py
This address one of the most popular requests from the community. With this PR, the web controller is always turned on no matter a joysticker is used or not. Please note the outputs of physical joystick overide the outputs of the local web controller, meaning that one can only use joystick to drive the car after enabling a joystick.
=> Support running webcontroller and physical joystick at the same time

docs/utility/ui.md, donkeycar/management/kivy_ui.py, donkeycar/management/ui.kv
* Make config parameters `PI_USERNAME` and `PI_HOSTNAME` optional, these are only needed in the car connector
* Add button to select copying tub contents (i.e. `rsync mycar/data/` vs `rsync mycar/data` which creates a new directory resulting in `mycar/data/data` on the host pc).
* Fixed path to startup screen image
* Added hint in docs for Kivy dependency on linux
=> Kivy UI fixes

donkeycar/templates/cfg_complete.py
It was redundant to the DRIVE_TRAIN_TYPE and  CONTROLLER_TYPE options
=> Remove HAVE_ROBHAT option, which is no longer used

donkeycar/parts/lidar.py
The old Skoltech RPLidar library is depreciated and no longer supports latest RPLidar firmware
=> Update Lidar part to use new Adafruit library

donkeycar/parts/oled.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py, install/pi/install.sh, setup.py
The Adafruit OLED library were were using has been deprecated and replaced by a CircuitPython-based version. This PR updates the OLED part to use the new library and adds a rotation option. 
Changes include: 
- Updated part
- Updated config file to add rotation option
- Updated install script to install CircuitPython dependencies
Tested on RPi.
=> Update OLED part to use non-deprecated library and add rotation

donkeycar/parts/tub_v2.py, donkeycar/tests/test_tub_v2.py
There is a bug in deleting the last n records of a tub. We fix it by correctly building the set of non-deleted indexes and removing the largest n entries from that.
=> Fix deletion of last records in tub

donkeycar/pipeline/database.py, donkeycar/pipeline/training.py
This got accidentally broken in 4.2 master. 
* Currently we have `donkey train --tub data --model pilot.h5` which will create the model in the directory `/model/pilot.h5`. 
* Previously we had explicitly give path to the models directory: `donkey train --tub data --model model/pilot.h5`. 
Here, we revert to the previous behaviour.
=> Revert to passing full path to model in training 

donkeycar/parts/actuator.py, donkeycar/parts/controller.py, donkeycar/parts/web_controller/web.py, donkeycar/templates/calibrate.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/cfg_simulator.py, donkeycar/templates/complete.py, donkeycar/tests/test_web_socket.py
Moved RC control to the Complete template and made it so you can use both RC in and out on the GPIO pins at the same time. This will support a RC hat for the Rpi.
Other changes:
--Got rid of the "USE_RC" config setting and instead conformed to standard for other controllers and actuators by creating a "pigpio_pwm" type for both
--I've done a global replace of the "SERVO_ESC" drivetrain type to "I2C_SERVO", which says what it is properly.
--Upped default loop speed to 40Hz
Tested with RC and joystick input, RC and I2C servo board output
Not working yet: auto record on throttle when in RC mode. Will refactor to work like Robohat MM1 part to gain that functionality
=> Refactored RC control for GPIO pins 

donkeycar/management/makemovie.py
This PR fixed the following two bugs:
- **tf2 version incomplatibility**
First,  the codes constructing saliency models  were incompatible with the tensorflow version 2. 
https://github.com/autorope/donkeycar/blob/20bf83c4f8bfe24bda151659e271a488bfa91f1b/donkeycar/management/makemovie.py#L186-L196
We should use the `GradientTape()` of tensorflow to calculate the gradient.
- **uint8 conversion bug**
Second, the conversion of RGB values from float (0.0, 1.0) to int (0, 255) was wrong, 
https://github.com/autorope/donkeycar/blob/20bf83c4f8bfe24bda151659e271a488bfa91f1b/donkeycar/management/makemovie.py#L239-L240
which creates artifacts as the bottom left figure shown. The red/yellow/blue parts are artifacts with RGB values over 255. Since some float values of the `image` array can be great …
=> fix saliency map bugs

install/envs/mac.yml
Move moviepy from conda -> pip as this seems not to be working with conda on OSX atm. Pip is pulling a slightly newer version that has been shown to work.
=> Fix moviepy installation on OSX

donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
I accidentally messed up and checked in some old code with the OLED PR. This restores the RC control (GPIO in and out) that had previously been approved and merged with Dev
=> Fixed RC control

donkeycar/__init__.py, setup.py
Put golden source of version into module's `__init__.py` so versions are in sync with `setup.py`.
=> Fix version in setup and align with module.

donkeycar/management/makemovie.py
The commit b544241fec146edcbb708edf58c813cef0b727b2 made a modification to the keras.py part on which the makemovie.py heavily depends. This results in errors of the code calling the keras part, https://github.com/autorope/donkeycar/blob/50f0831f824302693d7c2f479b95365fd7e41c05/donkeycar/management/makemovie.py#L76 https://github.com/autorope/donkeycar/blob/50f0831f824302693d7c2f479b95365fd7e41c05/donkeycar/management/makemovie.py#L147-L148 https://github.com/autorope/donkeycar/blob/50f0831f824302693d7c2f479b95365fd7e41c05/donkeycar/management/makemovie.py#L207
2.1 evaluate the effects of all output layers instead of one
2.2 correct the problematic math (blending the gradients of angle and throttle output layers together) from direct sum to square norm
2.3 calculate the saliency depending …
=> Fix bugs and Improve the approach of makemovie

donkeycar/templates/complete.py
https://github.com/autorope/donkeycar/issues/912
If you try to configure `CAMERA_TYPE="D435"` and `LIDAR_TYPE="RP"` simultaneously, the D435 part will NOT be correctly started when manage.py is run, but the RPLidar will not. RPLidar works fine if camera is MOCK.
The problem is a bug in manage.py (created from donkeycar/templates/complete.py). The code that configures that camera for some reason includes the lidar config. So on line 90 of https://github.com/autorope/donkeycar/blob/dev/donkeycar/templates/complete.py we start configuration of the camera with the 'stereo' camera, then on line 113 we 'elif' camera is "D435", then on line 136 we 'else' the other cameras. That 'else' block also contains the lidar configuration. So if we configure the D435 then the else is never executed and so …
=> Fix issue 912: Cannot start 2D lidar if using a RealSense D435

donkeycar/management/kivy_ui.py, donkeycar/parts/keras.py, donkeycar/templates/complete.py
_Currently_: the function expects the previous steering throttle values in the second argument
_Fix_: ignore the second argument and cache the previous return steering and throttle values from the network for the memory vector to be passed to the model.
Also fix the UI code accordingly. There are no changes to the car templates required.
=> Fix for memory model inferencing

donkeycar/templates/complete.py
- the complete.py template hooked up the encoder parts
using hard-coded value for mm_per_tick and ignored
the configuration for MM_PER_TICK.
- The RotaryEncoder was also using a default
value for the poll_delay so polling was incorrect
in anything except the default vehicle loop rate.
- This commit fixes the building of the pipeline
in complete.py to use the correct configuration.
It also calculates the poll_delay for the RotaryEncoder
based on the DRIVE_LOOP_HZ configuration.
=> fix-encoder-pipeline

donkeycar/parts/dgym.py
We previously used time.sleep to simulate the latency, but this method slows down the whole loop.
I added an image/info buffer to fix this issue.
what it does:
- when an image is received, store it into the buffer
- if an image has been long enough in the buffer use it as self.frame and remove it from the buffer.
If you have SIM_ARTIFICIAL_LATENCY=100, you should expect to have from 4 to 5 images in the buffer
tested on my machine with donkeycar in the sim
=> Added an image buffer to fix the artificial latency in sim

donkeycar/parts/controller.py
Same as PR #905 but rebased and squashed.
It's hard to pair PS3 controller to Jetson Nano however we still can use sixad, which continuously maintained by Retropie team, to pair and connect the controller. Details of instructions here and there(out of date), though referred to Pi but works on Nano too.
After successfully connecting the PS3 controller to Nano, there's a need to support the sixad version of PS3 button/axis mapping. Users can swap the PS3Joystick object with PS3JoystickSixAd in PS3JoystickController.init_js(). Tested with OEM PS3 controller on Nano 4GB kit.
Side note: we might want to update the docs about PS3 controller compatibility on Nano too.
=> Support for sixad ps3controller on Nano(2nd try)

donkeycar/__init__.py, setup.py
- installation was failing because setup was trying to
import from donkeycar before it was setup.
- setup.py imports __version__ from donkeycar;
that causes __init__.py to be loaded,
which tries to import pyfiglet.
We can't import from donkeycar in setup.py because it is not yet setup
- this fix uses pkg_resources.get_distribution() to
get the version set in setup.py and make it
available to the donkeycar code.
From now on we set the version in setup.py; it will be imported into the donkeycode.  This avoids the circular setup issue.
=> now donkey gets version from setup.py

donkeycar/templates/complete.py
ImageAugmentation is used during training. It is needed around line 467 of complete.py where cfg.TRANSFORMATIONS is used to determine if image augmentations will be applied during training. This breaks on a RaspberryPi when trying to drive because imgaug dependency is not installed. To fix this, we should move the import of ImageAugmentation from the top of complete.py to line 467 inside the if statement where it is needed, so no attempt is made to import it unless it is needed.
=> 937-import-imageaugmentation-causes-error

donkeycar/parts/object_detector/stop_sign_detector.py, donkeycar/parts/throttle_filter.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
Added a feature to force reverse the car for few iterations when it detected a stop sign, then stop the car until the stop sign is undetected. As when the car is driving at high speed, the stop sign could already be passed and is out of view before the car stops, which makes the car drive again. Therefore this reverse feature is added.
=> Updated stop sign detector part to allow reversing for few iterations

donkeycar/parts/fps.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
An fps counter that shows the current fps while running, and shows the fps list when shutdown.
=> Added fps counter part

donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py
[954-fix-csic-camera-capture](https://github.com/autorope/donkeycar/issues/954)
- csic camera would crash using resolution of 160x120
on a Jetson Nano
- this fixes it so it starts camera capture resolution to
be the same as the image resolution, which fixes that issue.
=> 954-fix-csic-camera-capture

donkeycar/management/base.py, setup.py
The `donkey tubhist` command got lost when migrating to 4.x. We are bringing it back here.
=> Add back support for tubhist

setup.py
- it was incorrectly installing the raspberry pi only library RPi.GPIO
- this caused issues where RPi.GPIO was imported.  This is because Jetson.GPIO, which is the Nvidia version of that library, creates an alias for RPi.GPIO so that code that uses RPi.GPIO will work on the nano but ONLY if it does NOT import RPi.GPIO
- Now we install Jetson.GPIO for the nano.
=> 963 Install Jetson.GPIO on [nano]

donkeycar/management/base.py, donkeycar/management/kivy_ui.py, donkeycar/management/ui.kv, donkeycar/pipeline/augmentations.py, donkeycar/pipeline/database.py, donkeycar/templates/cfg_basic.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/cfg_simulator.py, donkeycar/templates/cfg_square.py, setup.py
For training:
* In the image augmentation for training, increase default MULTIPLY range from [0, 1.5] to [0, 3.0] as sunlight effects seem to have larger brightness effects than 1.5
* Set default MODEL_CATEGORICAL_THROTTLE_RANGE to 0.8, as 0.5 is just too low. We have many tubs w/ throttle values larger 0.5.
For the UI:
* Fix small issues in the UI, in particular in the car screen, like the file transfer bars and error handling
* Add option to delete pilots from the pilot database
For the `donkey` command
* Add a new command `donkey models` which displays the trained pilots in the shell in the same way as in the UI.
General:
* Bump version to 4.3.1
=> Improvements to donkey UI and donkey command

donkeycar/parts/camera.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/complete.py, donkeycar/templates/cv_control.py
This PR addresses [Issue 961](https://github.com/autorope/donkeycar/issues/961) and a little more.  Basically our cameras could return None images if they did not start correctly.  The warmup was just a sleep(2) and no check was actually made to know that the camera started.  This could result in hard to understand downstream errors.  
- This PR fixes the 'PICAM', 'CSIC' and 'WEBCAM' camera drivers to check the the camera starts and is returning non-None images at initialization time so any camera initialization issue is caught early and with a clear error message.
- There are other camera configurations that have NOT been addressed by this PR, but should be looked at in a future PR; 'V4L' and 'CVCAM'.
- this PR also addresses the originally reported bug directly by protecting …
=> 961 protect from empty camera image

.github/workflows/superlinter.yml, donkeycar/parts/interpreter.py, install/envs/mac.yml, install/envs/ubuntu.yml, install/envs/windows.yml, setup.py
1) Two imports that are used in the UI were not correctly added to the install files
* pyyaml was missing in conda install files
* pyyaml and plotly were missing in setup.py 
2) Bumped the superlinter to v4 because of issue: https://github.com/github/super-linter/issues/2253
3) Also, moved tensorrt imports into function, so loading will not fail unless a tensorrt conversion is called. It seems windows 11 doesn't support tensorrt yet.
4) Bumped version bugfix digit
=> Fix missing import for UI and added windows support where tensorrt is not available

donkeycar/pipeline/augmentations.py, setup.py
Issue https://github.com/autorope/donkeycar/issues/970
Currently uses of Jetson Nano that use image augmentations or tranformations AND want to train on their Nano will get an exception because imgaug is not installed.  It is not installed because it conflicts with opencv, which is required for the CSIC camera.  The maintainer of imgaug has stated in related issues in the imgaug repo that he will not be fixing this.
This is a temporary hack to mock our ImageAugmentation class if imgaug cannot be imported.  This is a workaround so users of the Jetson Nano can train even if imgaug is not installed.  This allows them to train on their nano even if imgaug is not installed.
=> 970 imgaug workaround mock augmentations

donkeycar/parts/realsense435i.py
Add argument parsing in the `__main__` self test program.
- prior this this PR it would require altering the code to test different features of the RealSense 435i driver.
=> Add argument parser to realsense435i.py main

donkeycar/parts/actuator.py
- the throttle and steering passed to TwoWheelSteeringThrottle where just a 3/1000 over 1, but where triggering the check against a max of 1.
- this caused the differential drive cars to fail when trying to run the linear model.
- this commit simply clamps out of range values to the allowed range of -1 to 1 inclusive.
See @Rushil  issue in discord https://discordapp.com/channels/662098530411741184/671604367706554388/932156905818828861
=> clamp differential drive throttle and steering

donkeycar/parts/fastai.py, donkeycar/parts/interpreter.py, donkeycar/parts/keras.py, donkeycar/parts/pytorch/torch_data.py, donkeycar/pipeline/training.py, donkeycar/templates/complete.py, donkeycar/tests/test_train.py, donkeycar/utils.py, install/envs/mac.yml, install/envs/ubuntu.yml, install/envs/windows.yml, setup.py
This PR allows you to use Fast AI(pytorch) end to end in donkey car. I have tested training and driving with the simulator.
I have added a new type of model fastai_ so far linear is the only model implemented. More can be added in the future of course.
I have tried my best to emulate most of the function that Keras does but there are some idiosyncrasies between the two frameworks. 
These normal training and driving commands work.
python train.py --tubs data/ --model models/fastai_linear_model.pth --type fastai_linear
python manage.py drive --model models/fastai_linear_model.pth --type fastai_linear
I do realise that this PR comes without a heads up or warning so if its rejected that's fine. 
I do really like this project and the work that has been done, its just I prefer PyTorch to …
=> Adding FastAI(pytorch) as a first class citizen to the pipeline

donkeycar/management/joystick_creator.py
There is a syntax error in joystick creator.
=> fix syntax error in the joystick creator

donkeycar/parts/web_controller/web.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/cfg_path_follow.py, donkeycar/templates/complete.py, setup.py
Addresses Issue https://github.com/autorope/donkeycar/issues/989
The PWM_STEERING_PIN configuration values are used in several DRIVETRAIN_TYPE configurations, each with a different default value. If you just set the DRIVETRAIN_TYPE = "PWM_STEERING_THROTTLE", but don't uncomment the PWM_STEERING_PIN value, then the default of a different drivetrain get's used.
So a workaround is to just uncomment PWM_STEERING_PIN in the PWM_STEERING_THROTTLE sections.
This fix changes the newer drivetrain configuration into python dictionaries so all configuration are namespaced.
=> 989 namespace drivetrain configurations

donkeycar/parts/interpreter.py, donkeycar/utils.py, setup.py
There is an issue with the RPi version after merging of #986. The `pytorch` imports are not moved into the corresponding classes / functions, such now pytorch becomes a dependency when running code, like loading a model. This is non-wanted behaviour, because on RPi we don't install pytorch by default, and causes the `manage.py drive --model ` to fail. This fix moves the imports into the relevant classes/functions and fixes the issue.
=> Fix torch imports for rpi

donkeycar/__init__.py
Minor change to allow the root logger level to be set with an environment variable.  This makes it easy to run a different log level without changing code or configuration.
```python
LOG_LEVEL=DEBUG python manage.py drive
```
=> Set LOG_LEVEL environment variable to set log level

donkeycar/config.py, donkeycar/management/base.py, scripts/profile.py, setup.py
When training from the command line using `donkey train` we can now add a path to a different `myconfg.py` file. This was reported as issue #976.
=> Specify myconfig in training

donkeycar/parts/web_controller/web.py, setup.py
- fix for https://github.com/autorope/donkeycar/issues/996
- version="4.3.10"
=> - fix web controller recording state so it is latched.

donkeycar/parts/controller.py, setup.py
Fixes issue https://github.com/autorope/donkeycar/issues/1005  I tested this extensively with xbox controller.   
- while I was at it I changed logging to use a logger rather than print statements.
=> 1005 fix recording yet again

donkeycar/management/base.py, setup.py
The change was missing the addition of the `--myconfig` to the argument of the `train` command.
=> Fixed bug introduced in PR #997

donkeycar/parts/lidar.py, setup.py
There is a desire to integrate 2D lidar data more completely into the donkeycar pipeline - see [issue 910](https://github.com/autorope/donkeycar/issues/910).  In particular the idea is to integrate the lidar data with the front-facing camera image.  In addition there are some issues with regarding accuracy and latency.  This pull request endeavours to tackle both problems by creating new lidar parts for acquiring data from the RPLidar and plotting data. 
There a  few problems with the current RPLidar and LidarPlot parts.
- The RPLidar part would wait for a full scan to be available before updating any data.  For a lidar spinning at 5hz, this would incur a 200ms latency between data updates.
- The RPLidar part forced angles to be on integer degrees.  This is probably ok for near-obstacle …
=> Next gen lidar parts

donkeycar/parts/dgym.py, setup.py
fixes https://github.com/autorope/donkeycar/issues/1012
=> feat: dgym.py corrected for storing lidar data in sim

donkeycar/parts/datastore.py, setup.py
When using `AUTO_CREATE_NEW_TUB = True`, we import the legacy `datastore.py` module for the `TubHandler` class. However, that module specifies a `pandas` import at module level. We don't install `pandas` on RPi by default to keep the python package smaller. This behaviour has been reported in #1010.
This is fixed by:
* Move the pandas import from module level into the `Tub` and `TubGroup` classes as otherwise we have an import error on RPi when the config `AUTO_CREATE_NEW_TUB` is set to True.
* Bump the version.
=> Fix pandas import error on RPi

donkeycar/parts/gps.py, setup.py
- it turns out that it is common for the first set of
data returned by a gps module to include incorrectly
framed characters that break the unicode conversion.
- This change ignores exceptions thrown by the
unicode decoder and keeps on going until it
can read a correctly framed line.
=> Update NMEA parser to handle bad chars

donkeycar/parts/actuator.py, donkeycar/tests/test_actuator.py, donkeycar/utils.py, setup.py
When using the path_follow template with GPS I would often lose all steering control.  I had occasionally seen this in the standard complete.py template as well.  It turns out that the steering part would throw an exception on an out of range value and would kill the steering thread.  This PR fixes that problem.
- the CTE PID algorithm in path follow was predicting steering
values that were way out of the -1 to 1 range.
- This triggered a check that threw an exception.
- Since the part was being run in a thread, throwing the exception
kill the thread, so so the user would lose all steering control.
- Even the auto-pilot would lose steering.
- Part 1 of fix is to not throw an exception, but instead log
and error and return.
- Part 2 of the fix is to clamp all out of range values so
that if …
=> Fix loss of steering in path_follow template

donkeycar/memory.py, donkeycar/parts/explode.py, donkeycar/parts/web_controller/templates/base.html, donkeycar/parts/web_controller/templates/static/main.js, donkeycar/parts/web_controller/templates/static/style.css, donkeycar/parts/web_controller/templates/vehicle.html, donkeycar/parts/web_controller/web.py, donkeycar/templates/complete.py, setup.py
Issue https://github.com/autorope/donkeycar/issues/1022
This PR adds 5 general purpose buttons to the webui.  Presses of these buttons can be processed by other donkeycar parts as input values.
- reformatted webui layout into a 2 column layout that works better on a phone.  This is in anticipation of using the phone while using an RC controller we we can get similar functionality to a game controller.
- Also added code to hide the virtual joystick if it is not being used (if gamepad is being used).
- Add 5 buttons to the ui
- When a button is pressed the pressed state is sent to the donkeycar, which then latches the value.
- The latched value is then written into vehicle memory.
- Parts can detect button presses as input values and respond to them.
I've added code into the complete.py …
=> 1022 add programable buttons to webui

donkeycar/templates/calibrate.py, setup.py
This fixes the `calibrate.py` script that is copied into the car directory and connects to the web server's calibration page. The script was still using the old specification of PWM pins, but the complete template has been upgraded to the new definitions already. This PR addresses that inconsistency. We also remove some unfortunate code form the script. There is still a bad issue w/ monkeypatching going on.
=> Fix calibrate script

donkeycar/templates/complete.py
This is the first step in updating the path_follow.py template to use GPS.  This step is just to make the same sensor available in complete.py available to any template, and to simplify the complete.py template as well.  The full process for merging in the GPS branch can be found in [Issue 991}(https://github.com/autorope/donkeycar/issues/991#issuecomment-1242763724)
- refactored complete.py to move adding of common parts into functions that can be shared with other templates (path follow in particular).
- add_drivetrain() adds the configured drive train to the vehicle.
- add_odometry() adds configured encoders to the vehicle.
- get_camera()/add_camera() adds configured camera(s) to the vehicle.
- add_simulator() adds donkey gym if it is configured.
- add_user_controller() adds the webui …
=> Move adding camera, controller, drivetrain into functions

donkeycar/parts/gps.py, donkeycar/parts/kinematics.py, donkeycar/parts/logger.py, donkeycar/parts/path.py, donkeycar/parts/pipe.py, donkeycar/parts/serial_port.py, donkeycar/parts/text_writer.py, donkeycar/templates/cfg_path_follow.py, donkeycar/templates/path_follow.py, donkeycar/tests/test_kinematics.py, donkeycar/tests/test_path.py, donkeycar/utilities/dk_platform.py
[Issue 991](https://github.com/autorope/donkeycar/issues/991)
- Refactor gps part so serial input is done in a separate part.  The gps part only parses NMEA and outputs position in meters
- Add a part for reading serial input so serial code can be reused.
- Add a part for reading and writing delimited text files (like CSV or TSV)
- Update the path_follow template
- Support the same cameras, drivetrains, odometry and game controllers used by the complete.py template.
- allows use of web ui and controller buttons to set recording mode, load/save/reset paths, reset origin.
- use GPS as a source of (x, y) position.
This is been cherry picked from [921-gps-logger](https://github.com/autorope/donkeycar/tree/921-gps-logger) branch, which was successfully used in the Sept. 2022 Fremont outdoor …
=> 991 gps path follow

donkeycar/management/kivy_ui.py, setup.py
* When no tub or config is loaded, clicking transport buttons in the tub manager or pilot screen lead to ungraceful program aborts. Similarly clicking on augmentation controls. This is now handled better.
* Fixes in logger statements that lead to exceptions
* Improvement in the handling of the filter functionality in the tub manager screen: This filter will now be exported into the config such that it gets picked up in the training. This allows to use the filter in training without manually editing the config file.
=> UI bug fixes and improvements

donkeycar/templates/complete.py
Simulator is broken because SIM_RECORD_DISTANCE and SIM_RECORD_ORIENTATION is not present in config.py
Temp comment out until further fix
=> fix donkey gym bug

donkeycar/parts/robohat.py
Address issue https://github.com/autorope/donkeycar/issues/1053 
Robothat controller was not updated when we added code to make the game controllers and web controller cooperate.  I ported the recording latching code to the robot hat controller.
=> Robothat auto record on throttle

donkeycar/tests/test_web_socket.py
It seems that creating the `Mock` outside of the assignment fixes the instabilities in pytest.
=> Fix test_web_socket on OSX by creating mock outside of assignment.

donkeycar/templates/cfg_complete.py, donkeycar/templates/cfg_path_follow.py, donkeycar/templates/complete.py, donkeycar/templates/path_follow.py
The MPU6050 and MPU9250 allow for two different I2C addresses based on how an input line is set.  Our code does not support the secondary address, which is how the MM1 hat is setup.  This code allows those IMUs to be used with their secondary address.
- move construction of IMU part and addition to vehicle into a method in complete.py and make complete.py and path_follow.py use it.
- add IMU_ADDRESS defaulted to 0x68 to cfg_complete.py and cfg_path_follow.py
- make path follow use add_imu()
=> Add IMU_ADDRESS configuration

donkeycar/templates/complete.py, setup.py
The imu keras part expects an array for the imu data as a second input to the model. Creating a 3-liner vectorizer part to do this. This is a follow up from the discussion on discord: https://discord.com/channels/662098530411741184/1046926296116101180/1047206276066717746.
=> Fix imu input in the complete template. 

.github/workflows/python-package-conda.yml, donkeycar/parts/path.py, donkeycar/templates/cfg_complete.py, donkeycar/templates/cfg_path_follow.py, donkeycar/templates/cfg_simulator.py, donkeycar/templates/path_follow.py, donkeycar/tests/test_path.py, setup.py
Added support for variable throttle in `path_follow` by modifying the waypoint data structure to record the throttle at each waypoint. The feature may be turned off by setting `USE_CONSTANT_THROTTLE = True` in your `myconfig.py` (the flag is set to `False` by default).
Closes #1047.
=> Support velocity target on a waypoint in `path_follow`

donkeycar/parts/pipe.py, donkeycar/templates/complete.py
I added a serious bug in complete.py when I renamed the steering output from `'user/angle'` to `'user/steering'`.  It turns out the the literal string 'user/angle' is used all over the place in the deep learning pipeline and DonkeyUI, so we can't change it.  
This fix the fixes complete.py so it uses 'user/angle' and 'pilot/angle'.  This has been tested doing data collection, training and inference in autopilot mode.
The fix works by renaming the 'user/steering' value to 'user/angle' so both are in memory.  I found and fixed a bug in the Pipe() part that happens when renaming a single argument; Python's variable argument facility outputs a tuple with two elements when only a single argument was passed; I now check for that and explicitly send back the single argument.
=> 1104 fix user angle in deep learning

scripts/hsv_picker.py
This adds a script that allows a user to select an area on an image and sample the low and high HSV value to create a mask, like is used in the cv_control template.
We have found in testing that it can be difficult to figure out the HSV value range to use to detect the line and reject background.  This script makes it easier by allow the user to sample the video image.
=> Added hsv_picker.sh script to support cv template

donkeycar/parts/tub_v2.py
Fixes Issue https://github.com/autorope/donkeycar/issues/1098
I then when we went to the tub 2.0 format the code that is necessary to save the depth image was dropped.  This PR puts it back in.
=> Add back in the code that saves the 16bit grayscale png

donkeycar/parts/cv.py
- several of the color conversions were not correctly returning the converted image; returning None instead.  This caused a crash when they were used.
- this commit fixes those and makes all color conversions similar in how they return that converted image
- This also adds a new transform; a version of the trapezoid mask that takes values from the edges of the image like the crop transform does (rather than absoluted image coordinates as the pre-existing trapezoid transform does).
=> fix cv color conversions

donkeycar/parts/image_transformations.py, setup.py
This should be merged **_after_** PR https://github.com/autorope/donkeycar/pull/1133
I created this because I found bugs in the image transformations when I tried to create a chain of them.  I needed a test where I could try many combinations easily, so I created a function to create a image transform pipeline from a json file and created the `__main__` to use it.
You provide a json file that specifies a transformation pipeline and configures either an single image to be loaded or a camera to be used.  The image transformation pipeline is constructed and applied the configured image source and shown in an opencv window.
This json specifies a pipeline that applies canny edge detection to the image.
```
[
["RGB2GRAY"],
["BLUR", {}],
["CANNY", {}],
["CROP", {"left": 0, "top": 45, "right": 0, …
```
=> add a __main__ self-test configured with a json file

setup.py
Remove albumentations from jetson setup and move pyyaml into the required section, so it also installs on RPi. Also bump version.
=> Fixing setup.py for jetson

donkeycar/management/makemovie.py
In file: makemovie.py, method: `init_salient`, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not have identity an match with anything else. As a result, the identity check will have a logical short circuit and the program may have unintended behavior. 
The following binary operation
output_name is []
compares a newly created object with the identity operator which will always evaluate to False.
I suggested that the logical operation should be reviewed for correctness. 
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation …
=> Update test expression to remove logical short circuit

donkeycar/config.py, donkeycar/management/ui/common.kv, donkeycar/management/ui/pilot_screen.kv, donkeycar/management/ui/train_screen.kv, donkeycar/management/ui/ui.kv, donkeycar/pipeline/augmentations.py, donkeycar/pipeline/training.py, donkeycar/tests/setup.py, setup.cfg
* There seems to be a non-backward compatible change in matplotlib 3.9.* which we can resolve for the time being, by pegging it to version 3.8.* (https://discord.com/channels/662098530411741184/671604367706554388/1242225275941425193)
* There also seems to be a non-back compatible change in albumentations for empty compositions, for which we have a code fix here
* There is another backward incompatible change in `pytest`, hence pinning this to version 8.1 (https://github.com/mtreinish/stestr/issues/363)
* Also updated layout height for certain widgets in the UI under OSX which are too compressed
* Fixed tensor flow package name under OSX
* Fixed an older `__main__.__file__` expression in `load_config` which I found to be not working
=> Fix augmentations and matplotlib

donkeycar/parts/path.py
Should return three values, but in the case of None it only returned two, causing an error. Thanks to Dirk for debugging
=> Fix  bug in path.py
